# Default values for web-apigw.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
pathBase: /web-apigw

image:
  repository: envoyproxy/envoy
  tag: v1.28-latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "web-apigw"

service:
  type: ClusterIP
  port: 80
  adminPort: 8001
  httpNodePort: 31103

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  hosts:
    - host: promag.local
      paths: [
        /web-apigw(/|$)(.*)
      ]
  tls: []

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

envoy:
  configPath: /etc/envoy

probes:
  liveness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 15
    port: 8001
  readiness:
    path: /ready
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 8001
