image: 
  tag: 9-community
persistence: 
  enabled: true
  existingClaim: sonar-pvc
resources: 
  limits: 
    cpu: 1000m
    memory: 1536Mi
  requests: 
    cpu: 500m
    memory: 1024Mi
ingress: 
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts: 
    - name: sonar.promag.minhtrandev.com
      path: /
  tls: 
    - hosts: 
      - sonar.promag.minhtrandev.com
      secretName: sonar-dev-tls
database: 
  type: postgresql
postgresql: 
  enabled: false
  postgresqlServer: postgresql
  postgresqlUsername: postgres
  postgresqlPasswordSecret: app-env-secret
  postgresqlDatabase: sonarDB-dev
