<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.1.2"/>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.1.2"/>
        <PackageReference Include="MassTransit.SerilogIntegration" Version="5.5.6"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Configuration.OpenTelemetry\Configuration.OpenTelemetry.csproj"/>
    </ItemGroup>


</Project>
