# Default values for graph-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: REPOSITORY_PATH
  tag: latest
  pullPolicy: Always

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: "graph-gateway"

service:
  type: ClusterIP
  port: 5100
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: cert-manager
    networking.gke.io/v1beta1.FrontendConfig: graph-gateway-fe-config
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    #   grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  hosts:
    - host: graph.promag.minhtrandev.com
      paths: [ / ]

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /health
    timeoutSeconds: 5
    initialDelaySeconds: 10
    periodSeconds: 30

env:
  normal:
    - name: App__HealthCheckEnabled
      value: 'true'

    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: PathBase
      value: /gateway

    - name: Logging__Seq__Enabled
      value: 'true'
    - name: Logging__Seq__Url
      value: http://seq:5341/
    - name: Logging__MinimumLevel__Default
      value: Warning

    - name: OpenTelemetry__Enabled
      value: 'true'
    - name: OpenTelemetry__zipkinEndpoint
      value: http://zipkin:9411/api/v2/spans

    - name: Services__CommunicationService__Url
      value: http://communication-api:5002
    - name: Services__CommunicationService__GrpcUrl
      value: http://communication-api:15002

    - name: Services__PersonalService__Url
      value: http://personal-data-api:5003
    - name: Services__PersonalService__GrpcUrl
      value: http://personal-data-api:15003

    - name: Services__MasterDataService__Url
      value: http://master-data-api:5004
    - name: Services__MasterDataService__GrpcUrl
      value: http://master-data-api:15004

    - name: Services__PortalService__Url
      value: http://portal-api:5001
    - name: Services__PortalService__GrpcUrl
      value: http://portal-api:15001

    - name: Services__IdentityService__Url
      value: http://identity-api:5101
    - name: Services__IdentityService__GrpcUrl
      value: http://identity-api:15101

  secret:
    - name: Logging__Seq__ApiKey
      key: Seq.Apikey
