# Default values for personal-data-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:32000/personal-data-api
  tag: local
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "personal-data-api"

service:
  type: ClusterIP
  port: 5003
  grpcPort: 15003

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

probes: []

env:
  normal:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

    - name: App__HealthCheckEnabled
      value: true

    - name: MessageBus__TransportType
      value: RabbitMQ
    - name: MessageBus__RabbitMQ__username
      value: promag
    - name: MessageBus__RabbitMQ__Url
      value: amqp://rabbitmq

    - name: Logging__Seq__Enabled
      value: false
    - name: Logging__Seq__Url
      value: http://seq:5341/
    - name: Logging__MinimumLevel__Default
      value: Error

    - name: Services__IdentityService__Url
      value: http://identity-api:5101
    - name: Services__IdentityService__ExternalUrl
      value: http://localhost:31101 #change to host IP if do not use NAT
    - name: Services__IdentityService__GrpcUrl
      value: http://identity-api:15101
    - name: Storage__Stores__filesystem__Parameters__Path
      value: /mnt/promag
    - name: Services__MasterDataService__GrpcUrl
      value: http://master-data-api:15004

    - name: OpenTelemetry__Enabled
      value: false
    - name: OpenTelemetry__zipkinEndpoint
      value: http://zipkin:9411/api/v2/spans

  secret:
    - name: ConnectionStrings__personalData
      key: ConnectionString.PersonalData
    - name: Logging__Seq__ApiKey
      key: Seq.Apikey
    - name: MessageBus__RabbitMQ__password
      key: RabbitMQ.Password
