# Default values for gateways.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:32000/gateways
  tag: local
  pullPolicy: Always

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: "gateways"

service:
  type: NodePort
  port: 5100
  httpNodePort: 31100

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: promag.local
      paths: [ /gateway ]

  tls: [ ]

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

probes: [ ]

env:
  normal:
    - name: App__HealthCheckEnabled
      value: true

    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: PathBase
      value: /gateway

    - name: Logging__Seq__Enabled
      value: false
    - name: Logging__Seq__Url
      value: http://seq:5341/
    - name: Logging__MinimumLevel__Default
      value: Error

    - name: OpenTelemetry__Enabled
      value: false
    - name: OpenTelemetry__zipkinEndpoint
      value: http://zipkin:9411/api/v2/spans

    - name: Services__CommunicationService__Url
      value: http://communication-api:5002
    - name: Services__CommunicationService__GrpcUrl
      value: http://communication-api:15002

    - name: Services__PersonalService__Url
      value: http://personal-data-api:5003
    - name: Services__PersonalService__GrpcUrl
      value: http://personal-data-api:15003

    - name: Services__MasterDataService__Url
      value: http://master-data-api:5004
    - name: Services__MasterDataService__GrpcUrl
      value: http://master-data-api:15004

    - name: Services__PortalService__Url
      value: http://portal-api:5001
    - name: Services__PortalService__GrpcUrl
      value: http://portal-api:15001

    - name: Services__IdentityService__Url
      value: http://identity-api:5101
    - name: Services__IdentityService__GrpcUrl
      value: http://identity-api:15101

    - name: ReverseProxy__Routes__PersonalRoute__ClusterId
      value: 'PersonalCluster'
    - name: ReverseProxy__Routes__PersonalRoute__Match__Path
      value: '/personal/{**catch-all}'
    - name: ReverseProxy__Routes__PersonalRoute__Transforms__0__PathPattern
      value: "{**catch-all}"
    - name: ReverseProxy__Clusters__PersonalCluster__Destinations__PersonalDestination__Address
      value: http://localhost:5003

  secret:
    - name: Logging__Seq__ApiKey
      key: Seq.Apikey
