rabbitmq:
  image: rabbitmq:4.2.2-management

  replicas: 1

  persistence:
    enabled: true
    storageClassName: standard
    storage: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    type: ClusterIP