apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-apigw.fullname" . }}
  labels:
    {{- include "web-apigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "web-apigw.selectorLabels" . | nindent 4 }}
