apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}

  # Image
  image: {{ .Values.rabbitmq.image | quote }}

  # Pod resources
  resources:
{{ toYaml .Values.rabbitmq.resources | indent 4 }}

  # Persistence
{{- if .Values.rabbitmq.persistence.enabled }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.persistence.storageClassName | quote }}
    storage: {{ .Values.rabbitmq.persistence.storage | quote }}
{{- end }}

  # Service exposure
  service:
    type: {{ .Values.rabbitmq.service.type }}