apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-default-user
  namespace: {{ .Values.namespace }}
stringData:
  default_user.conf: |
    default_user = {{ .Values.rabbitmq.auth.username }}
    default_pass = {{ .Values.rabbitmq.auth.password }}
  username: {{ .Values.rabbitmq.auth.username }}
  password: {{ .Values.rabbitmq.auth.password }}
type: Opaque