{{- if .Values.externalEmailSender.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: external-email-sender
spec:
  type: ExternalName
  externalName: {{ .Values.externalEmailSender.host }}
{{- end }}
