{{- if .Values.externalEmailSender.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: external-email-sender
spec:
  ports:
    - port: 587
      targetPort: 587
      protocol: TCP
      name: smtp
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-email-sender
subsets:
  - addresses:
      - ip: 198.54.122.135
    ports:
      - port: 587
{{- end }}
