# Default values for identity-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: 
  repository: promag/identity-api
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "identity-api"

service: 
  type: ClusterIP
  port: 5101
  grpcPort: 15101

ingress: 
  enabled: true
  annotations: {
      kubernetes.io/ingress.class: nginx,
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    }
  hosts: 
    - host: id.dev.promag.cf
      paths: [
          /
        ]

  tls: 
    - hosts: 
      - id.dev.promag.cf
      secretName: id-dev-tls

resources: 
  limits: 
    cpu: 200m
    memory: 256Mi
  requests: 
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

probes: 
  liveness: 
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness: 
    path: /health
    timeoutSeconds: 5
    initialDelaySeconds: 10
    periodSeconds: 30

env: 
  normal: 
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: PathBase
      value: /

    - name: App__HealthCheckEnabled
      value: true

    - name: OpenTelemetry__Enabled
      value: true
    - name: OpenTelemetry__zipkinEndpoint
      value: http://zipkin:9411/api/v2/spans

    - name: Logging__Seq__Enabled
      value: true
    - name: Logging__Seq__Url
      value: http://seq:5341/
    - name: Logging__MinimumLevel__Default
      value: Error

    - name: MessageBus__TransportType
      value: RabbitMQ
    - name: MessageBus__RabbitMQ__username
      value: promag
    - name: MessageBus__RabbitMQ__Url
      value: amqp://rabbitmq

    - name: IdentityServiceOptions__ExternalIdentityBaseUrl
      value: https://id.dev.promag.cf

  secret: 
    - name: ConnectionStrings__identity
      key: ConnectionString.Identity
    - name: Logging__Seq__ApiKey
      key: Seq.Apikey
    - name: MessageBus__AzureSB__ConnectionString
      key: azureSB.ConnectionString
    - name: MessageBus__RabbitMQ__password
      key: RabbitMQ.Password
