fullnameOverride: secret

info:
  connectionStrings:
    identity: "U2VydmVyPXBvc3RncmVzcWw7UG9ydD01NDMyO0RhdGFiYXNlPVByb21hZztVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPVBAc3N3MHJkOw=="
    personalData: "U2VydmVyPXBvc3RncmVzcWw7UG9ydD01NDMyO0RhdGFiYXNlPVByb21hZztVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPVBAc3N3MHJkOw=="
    portal: "U2VydmVyPXBvc3RncmVzcWw7UG9ydD01NDMyO0RhdGFiYXNlPVByb21hZztVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPVBAc3N3MHJkOw=="
    masterData: "U2VydmVyPXBvc3RncmVzcWw7UG9ydD01NDMyO0RhdGFiYXNlPVByb21hZztVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPVBAc3N3MHJkOw=="
  rabbitMQ:
    username: "cHJvbWFn"
    password: "UEBzc3cwcmQ="
  azureSB:
    connectionString: "bi9h"
  seq:
    apikey: "RjNDY0hZVHBhTkdiZjBlRk10YlI="
  postgresql:
    password: "UEBzc3cwcmQ="
