global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'graphQL-gateway'
    static_configs:
      - targets: ['graph-gateway:5100']
  - job_name: 'identity-api'
    static_configs:
      - targets: ['identity-api:5101']
  - job_name: 'communication-api'
    static_configs:
      - targets: ['communication-api:5002']
  - job_name: 'portal-api'
    static_configs:
      - targets: ['portal-api:5001']