apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
  labels:
{{ include "secret.labels" . | indent 4 }}
type: Opaque
data:
  ConnectionString.Identity: {{ .Values.info.connectionStrings.identity }}
  ConnectionString.PersonalData: {{ .Values.info.connectionStrings.personalData }}
  ConnectionString.Portal: {{ .Values.info.connectionStrings.portal }}
  ConnectionString.MasterData: {{ .Values.info.connectionStrings.masterData }}
  RabbitMQ.Password: {{ .Values.info.rabbitMQ.password }}
  Seq.Apikey: {{ .Values.info.seq.apikey }}
  Postgresql.Password: {{ .Values.info.postgresql.password }}
  rabbitmq-password: {{ .Values.info.rabbitMQ.password }}
  postgresql-password: {{ .Values.info.postgresql.password }}
  postgresql-postgres-password: {{ .Values.info.postgresql.password }}
  postgres-password: {{ .Values.info.postgresql.password }}
