apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
  labels:
{{ include "secret.labels" . | indent 4 }}
type: Opaque
data:
  ConnectionString.Identity: {{ .Values.info.connectionStrings.identity }}
  ConnectionString.PersonalData: {{ .Values.info.connectionStrings.personalData }}
  ConnectionString.Portal: {{ .Values.info.connectionStrings.portal }}
  ConnectionString.MasterData: {{ .Values.info.connectionStrings.masterData }}

  RabbitMQ.Password: {{ .Values.info.rabbitMQ.password }}
  rabbitmq-password: {{ .Values.info.rabbitMQ.password }}

  Seq.Apikey: {{ .Values.info.seq.apikey }}

  Postgresql.Password: {{ .Values.info.postgresql.password }}
  postgresql-password: {{ .Values.info.postgresql.password }}
  postgresql-postgres-password: {{ .Values.info.postgresql.password }}
  postgres-password: {{ .Values.info.postgresql.password }}

  redis-password: {{ .Values.info.redis.password }}
  Redis.Configuration: {{ .Values.info.redis.configuration }}

  MailKit.Password: {{ .Values.info.mailKit.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-default-user
  namespace: {{ .Release.Namespace }}
data:
  default_user.conf: {{ printf "default_user = %s\ndefault_pass = %s" (.Values.info.rabbitMQ.username | b64dec) (.Values.info.rabbitMQ.password | b64dec) | b64enc }}
  host: dmF1bHQtZGVmYXVsdC11c2VyLmRlZmF1bHQuc3Zj
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: {{ .Values.info.rabbitMQ.username }}
  password: {{ .Values.info.rabbitMQ.password }}
type: Opaque