<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\BuildingBlocks\Configuration.Metrics\Configuration.Metrics.csproj"/>
        <ProjectReference Include="..\..\BuildingBlocks\Configuration.OpenTelemetry\Configuration.OpenTelemetry.csproj"/>
        <ProjectReference Include="..\..\BuildingBlocks\Configuration.Vault\Configuration.Vault.csproj"/>
        <ProjectReference Include="..\..\BuildingBlocks\GraphQl\GraphQl.csproj"/>
        <ProjectReference Include="..\..\BuildingBlocks\Shared\Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\..\_schema\proto\promag\pagination\v1\pagination.proto" Link="protobuf\pagination.proto" AdditionalImportDirs="..\..\_schema\proto\"/>
        <Protobuf Include="..\..\_schema\proto\promag\common\v1\common.proto" Link="protobuf\common.proto" AdditionalImportDirs="..\..\_schema\proto\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="7.1.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="7.0.0"/>
        <PackageReference Include="Grpc.Net.ClientFactory" Version="2.59.0"/>
        <PackageReference Include="Grpc.Tools" Version="2.59.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.HeaderPropagation" Version="7.0.12"/>
        <PackageReference Include="Yarp.ReverseProxy" Version="2.1.0"/>
    </ItemGroup>

</Project>
