fullnameOverride: seq
image: 
  tag: latest
resources: 
  limits: 
    cpu: 300m
    memory: 256Mi
  requests: 
    cpu: 300m
    memory: 256Mi
persistence: 
  enabled: true
  existingClaim: seq-pvc
auth: 
  enabled: false
ingress: 
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts: 
    - seq.promag.minhtrandev.com
  tls: 
    - hosts: 
      - seq.promag.minhtrandev.com
      secretName: seq-dev-tls
