fullnameOverride: rabbitmq
persistence:
  enabled: false
  existingClaim: rabbitmq-pvc
auth:
  username: promag
  existingPasswordSecret: app-env-secret

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
