admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: promag_backend_route
                  virtual_hosts:
                    - name: promag_backend
                      domains:
                        - "*"
                      routes:
                        - name: "p-short"
                          match:
                            prefix: "/p/"
                          route:
                            auto_host_rewrite: true
                            prefix_rewrite: "/"
                            cluster: personaldata
                http_filters:
                  - name: envoy.router
                access_log:
                  - name: envoy.file_access_log
                    filter:
                      not_health_check_filter: {}
                    config:
                      path: "/tmp/access.log"
  clusters:
    - name: personaldata
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: host.docker.internal
            port_value: 5003
