name: Certificates Manager Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - k8s/cert-manager.yaml
      - .github/workflows/cert-manager.yml

jobs:
  deploy:
    name: Deploy Certificates Manager
    runs-on: ubuntu-latest
    env:
      # Google Cloud variables
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      PROJECT_NAME: promag
      REGION: us-central1
      LOCATION: us-central1-a

      # Kubernetes variables
      CLUSTER_NAME: sit-cluster
      NAMESPACE: prod
      VALUES_FILE: cert-manager.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Install the GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Apply changes
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --location $LOCATION
          
          kubectl apply -f k8s/$VALUES_FILE --namespace $NAMESPACE