name: Identity API

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - src/Identity/**/*

jobs:
  deploy:
    name: Deploy Identity API
    runs-on: ubuntu-latest
    env:
      PROJECT_REGION: us-central1
      IMAGE: identity-api:latest
      ARTIFACTS_REGISTRY: promag

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the GCloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t {{ PROJECT_REGION }}-docker.pkg.dev/{{ secrets.GOOGLE_PROJECT }}/{{ ARTIFACTS_REGISTRY }}/{{ IMAGE }} .
          docker push {{ PROJECT_REGION }}-docker.pkg.dev/{{ secrets.GOOGLE_PROJECT }}/{{ ARTIFACTS_REGISTRY }}/{{ IMAGE }}
