name: Redis Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - k8s/charts/redis/**/*
      - .github/workflows/redis.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      # Google Cloud variables
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      PROJECT_NAME: promag
      REGION: us-central1
      LOCATION: us-central1-a

      # Kubernetes variables
      CLUSTER_NAME: sit-cluster
      NAMESPACE: prod
      CHART: redis
      CHART_REPO: bitnami/redis
      DEPLOYMENT: redis
      VALUES_FILE: values.yaml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Install the GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Deploy to GKE
        run: |-
          gcloud container clusters get-credentials $CLUSTER_NAME --location $LOCATION

          helm upgrade --install --namespace $NAMESPACE -f k8s/charts/$CHART/$VALUES_FILE $CHART $CHART_REPO
